language: rust
cache: cargo

before_script:
  - set -e

script:
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - echo '<head><meta http-equiv="refresh" content="0; URL=aimc/index.html" /></head>' > target/doc/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: target/doc
    on:
      branch: master
      rust: stable

notifications:
  email:
    on_success: never

env:
  global:
    secure: ihE5jTeM2g2CwqShrz4nKbnVgN+5IuaZ+PygLVp3wFUuNh8MbUsy8t1C6HXJRYzQHB67/vBuR+S//4LNBD12KZ7P8IEgkrxypD8BcJaU9Y0dXfqLrH2pushHYAGnmsbMIySLwGumBFN/aYaAsN00ef/KzEssEDR5R+oIvvqkh1CkQR12pXrKvE2+N7UxvK/3/Cb9UZA+5P3FRCxct2G+J8Rfhb4AA5acUODf/wwzRCyvhAgSovnSLQPHkvSASSI8m936PfsB+nKsfck144v7Ag9/tTRJbAXsP56Uj4LKRMfAv3PqSlp9kIv4S9mAQIq6dUJIZjewbPaawAB4x7Ha1HJghduqpyXzhKojiDh9E7UsEr1XZNG1DjBs8nK4N+i6pf053CAR12T5LgOMrTBohQPeQ0HOCZjJwmrgeGeTTaMTBlonRyetNwOXLSH+WQWiX3MJi6fD4WPq0j/ZRMf40zky5tNAMgUTYLnA6pAa54hSeAFa2MSjxJ7CTdW5hokbjjn7ZTxFb8uZlmsh2VseM8ZCwfO/JjZDX9YJ3liV1taG9hzlzJr8ozEwEvg2gSBg5c/Xh/HD25mraxaJI1zGrL/gGC2ogb/DSQEdhTBgzpuCZFyQv++852j1y5lKFH683YDR1U3o6ao1oxFoYXj/GTXUmtM7rZv24yacBkY3kYg=
