language: rust
cache: 
  - cargo

before_script:
  - set -e

matrix:
  include:

  # Make sure the WASM+Vue frontend compiles
  - rust: beta
    name: frontend
    env: 
      - RUST_BACKTRACE=1
    before_script:
      - rustup target add wasm32-unknown-unknown
      - export PATH="$HOME/.cargo/bin:$PATH"
      - command -v wasm-pack || cargo install --debug wasm-pack
      - npm install --global yarn
    script:
      - cd sim
      - wasm-pack build
      - cd pkg && yarn link 
      - cd ../../frontend
      - yarn link aimc_sim
      - yarn install
      - yarn build
      - yarn test

  # And the rest of the project
  - rust: nightly
    name: backend
    env: RUST_BACKTRACE=1
    script:
      - cargo build --all --verbose
      - cargo test --all --verbose
    before_deploy:
      - cargo doc --verbose
      - echo '<head><meta http-equiv="refresh" content="0; URL=aimc_hal/index.html" /></head>' > target/doc/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: target/doc
    on:
      branch: master
      rust: nightly

notifications:
  email:
    on_success: never
