language: rust
cache: cargo
rust:
  - "1.31.0"
  - stable
  - nightly

before_script:
  - set -e

script:
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - echo '<head><meta http-equiv="refresh" content="0; URL=aimc/index.html" /></head>' > target/doc/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: target/doc
    on:
      branch: master
      rust: nightly

notifications:
  email:
    on_success: never
