language: rust
cache: 
  - cargo
  - yarn

before_script:
  - set -e

matrix:
  include:

  # Make sure the WASM+Vue frontend compiles
  - rust: beta
    name: frontend
    env: 
      - RUST_BACKTRACE=1
      - TARGET=wasm32-unknown-unknown
    before_script:
      - rustup target add $TARGET
      - npm install --global yarn
    script:
      - cargo check --all
      - cargo check --all --target $TARGET
      - cargo check --all                  --no-default-features
      - cargo check --all --target $TARGET --no-default-features
      - cargo check --all                  --no-default-features --features console_error_panic_hook
      - cargo check --all --target $TARGET --no-default-features --features console_error_panic_hook
      - cd frontend
      - yarn install
      - yarn build
      - yarn test

  # And the rest of the project
  - rust: nightly
    name: backend
    env: RUST_BACKTRACE=1
    script:
      - cargo build --all --verbose
      - cargo test --all --verbose
    before_deploy:
      - cargo doc --verbose
      - echo '<head><meta http-equiv="refresh" content="0; URL=aimc_hal/index.html" /></head>' > target/doc/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: target/doc
    on:
      branch: master
      rust: nightly

notifications:
  email:
    on_success: never
